#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const APPS_DIR = path.join(__dirname, '..', 'apps');
const README_PATH = path.join(__dirname, '..', 'README.md');
const APPS_JSON_PATH = path.join(__dirname, '..', 'apps.json');

function loadApps() {
  const apps = [];
  if (!fs.existsSync(APPS_DIR)) return apps;

  const dirs = fs.readdirSync(APPS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  for (const dir of dirs) {
    const yamlPath = path.join(APPS_DIR, dir, 'app.yaml');
    const logoPath = path.join(APPS_DIR, dir, 'logo.png');

    if (!fs.existsSync(yamlPath)) {
      console.warn(`Warning: No app.yaml found in ${dir}`);
      continue;
    }

    try {
      const content = fs.readFileSync(yamlPath, 'utf8');
      const app = yaml.load(content);
      app._slug = dir;
      app._hasLogo = fs.existsSync(logoPath);
      apps.push(app);
    } catch (err) {
      console.error(`Error loading ${yamlPath}: ${err.message}`);
    }
  }

  return apps;
}

function generateAnchor(name) {
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '');
}

// Sanitize text for safe markdown embedding
function sanitizeMd(text) {
  return String(text)
    .replace(/[<>&"'`]/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&#39;', '`': '&#96;' }[c]))
    .replace(/\[/g, '\\[')
    .replace(/\]/g, '\\]');
}

function generateAppCard(app) {
  const logoUrl = app._hasLogo
    ? `./apps/${app._slug}/logo.png`
    : 'https://via.placeholder.com/64?text=App';

  const openSourceBadge = app.open_source
    ? ` [![Open Source](https://img.shields.io/badge/Open%20Source-green)](${app.open_source})`
    : '';

  const tags = app.tags.map(tag => `\`${tag}\``).join(' ');

  const docs = app.docs
    ? `\n\n[Documentation](${app.docs})`
    : '';

  const safeName = sanitizeMd(app.name);
  const safeDesc = sanitizeMd(app.description);

  return `### [${safeName}](${app.url})

<img src="${logoUrl}" alt="${safeName} logo" width="64" height="64">

${safeDesc}

${tags}${openSourceBadge}${docs}

---`;
}

function generateReadme(apps) {
  const sorted = [...apps].sort((a, b) =>
    a.name.toLowerCase().localeCompare(b.name.toLowerCase())
  );

  const toc = sorted.map(app => {
    const anchor = generateAnchor(app.name);
    return `- [${app.name}](#${anchor})`;
  }).join('\n');

  const cards = sorted.map(generateAppCard).join('\n\n');

  return `# Works with Ofox

A curated list of apps and tools built with [Ofox](https://ofox.ai). Ofox is a unified gateway — one API key to reach Claude, GPT, Gemini, DeepSeek and more.

## What is Ofox?

[Ofox](https://ofox.ai) gives you a single interface to AI models across providers, through one API.

**Why Ofox:**
- One interface to many AI models
- Automatic fallback and load balancing
- No vendor lock-in

## Get an API key

1. Sign up at [ofox.ai](https://ofox.ai)
2. Add credits and generate an API key in the dashboard
3. Use it in any app below, or integrate it into your own project

<!-- DO NOT EDIT THIS FILE DIRECTLY -->
<!-- This file is auto-generated. See CONTRIBUTING.md for how to add your app. -->

## Contents

${toc}

## Apps

${cards}

## Add your app

Want your app on this list? See [CONTRIBUTING.md](CONTRIBUTING.md).

---

Powered by [Ofox AI](https://ofox.ai) · One key, every model
`;
}

function main() {
  console.log('Loading apps...');
  const apps = loadApps();
  console.log(`Found ${apps.length} app(s)`);

  console.log('Generating README...');
  const readme = generateReadme(apps);
  fs.writeFileSync(README_PATH, readme);
  console.log(`README.md generated with ${apps.length} app(s)`);

  // Generate apps.json for website consumption
  const appsJson = apps.map(app => ({
    slug: app._slug,
    name: app.name,
    description: app.description,
    url: app.url,
    docs: app.docs || null,
    tags: app.tags,
    openSource: app.open_source || null,
    dateAdded: app.date_added,
  }));
  fs.writeFileSync(APPS_JSON_PATH, JSON.stringify(appsJson, null, 2) + '\n');
  console.log('apps.json generated');
}

main();
