#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const APPS_DIR = path.join(__dirname, '..', 'apps');
const README_PATH = path.join(__dirname, '..', 'README.md');
const APPS_JSON_PATH = path.join(__dirname, '..', 'apps.json');

const TAG_LABELS = {
  chat: '聊天',
  coding: '编程',
  productivity: '效率',
  creative: '创意',
  research: '研究',
  education: '教育',
  data: '数据',
  media: '媒体',
  devops: 'DevOps',
  other: '其他',
};

function loadApps() {
  const apps = [];
  if (!fs.existsSync(APPS_DIR)) return apps;

  const dirs = fs.readdirSync(APPS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  for (const dir of dirs) {
    const yamlPath = path.join(APPS_DIR, dir, 'app.yaml');
    const logoPath = path.join(APPS_DIR, dir, 'logo.png');

    if (!fs.existsSync(yamlPath)) {
      console.warn(`Warning: No app.yaml found in ${dir}`);
      continue;
    }

    try {
      const content = fs.readFileSync(yamlPath, 'utf8');
      const app = yaml.load(content);
      app._slug = dir;
      app._hasLogo = fs.existsSync(logoPath);
      apps.push(app);
    } catch (err) {
      console.error(`Error loading ${yamlPath}: ${err.message}`);
    }
  }

  return apps;
}

function generateAnchor(name) {
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^\w-]/g, '');
}

// Sanitize text for safe markdown embedding
function sanitizeMd(text) {
  return String(text)
    .replace(/[<>&"'`]/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&#39;', '`': '&#96;' }[c]))
    .replace(/\[/g, '\\[')
    .replace(/\]/g, '\\]');
}

function generateAppCard(app) {
  const logoUrl = app._hasLogo
    ? `./apps/${app._slug}/logo.png`
    : 'https://via.placeholder.com/64?text=App';

  const openSourceBadge = app.open_source
    ? ` [![Open Source](https://img.shields.io/badge/Open%20Source-green)](${app.open_source})`
    : '';

  const tags = app.tags.map(tag => `\`${tag}\``).join(' ');

  const docs = app.docs
    ? `\n\n[Documentation](${app.docs})`
    : '';

  const safeName = sanitizeMd(app.name);
  const safeDesc = sanitizeMd(app.description);

  return `### [${safeName}](${app.url})

<img src="${logoUrl}" alt="${safeName} logo" width="64" height="64">

${safeDesc}

${tags}${openSourceBadge}${docs}

---`;
}

function generateReadme(apps) {
  const sorted = [...apps].sort((a, b) =>
    a.name.toLowerCase().localeCompare(b.name.toLowerCase())
  );

  const toc = sorted.map(app => {
    const anchor = generateAnchor(app.name);
    return `- [${app.name}](#${anchor})`;
  }).join('\n');

  const cards = sorted.map(generateAppCard).join('\n\n');

  return `# Works with Ofox / Ofox 应用展示墙

基于 [Ofox](https://ofox.ai) 构建的应用和工具精选列表。Ofox 提供统一接口，一个 API Key 访问 Claude、GPT、Gemini、DeepSeek 等顶尖 AI 模型。

## 什么是 Ofox？

[Ofox](https://ofox.ai) 提供统一的 AI 模型接口，通过一个 API 访问多家供应商的模型。

**为什么选择 Ofox：**
- 一个接口访问多家 AI 模型
- 自动故障转移和负载均衡
- 无供应商锁定

## 获取 API Key

1. 在 [ofox.ai](https://ofox.ai) 注册账号
2. 充值并在控制台生成 API Key
3. 在下面任意应用中使用，或集成到你自己的项目

<!-- DO NOT EDIT THIS FILE DIRECTLY -->
<!-- 此文件由脚本自动生成，请参阅 CONTRIBUTING.md 了解如何添加你的应用 -->

## 目录

${toc}

## 应用列表

${cards}

## 添加你的应用

想把你的应用添加到这个列表？参见 [CONTRIBUTING.md](CONTRIBUTING.md)。

---

Powered by [Ofox AI](https://ofox.ai) \u00B7 你的 AI 伙伴
`;
}

function main() {
  console.log('Loading apps...');
  const apps = loadApps();
  console.log(`Found ${apps.length} app(s)`);

  console.log('Generating README...');
  const readme = generateReadme(apps);
  fs.writeFileSync(README_PATH, readme);
  console.log(`README.md generated with ${apps.length} app(s)`);

  // Generate apps.json for website consumption
  const appsJson = apps.map(app => ({
    slug: app._slug,
    name: app.name,
    description: app.description,
    url: app.url,
    docs: app.docs || null,
    tags: app.tags,
    openSource: app.open_source || null,
    dateAdded: app.date_added,
  }));
  fs.writeFileSync(APPS_JSON_PATH, JSON.stringify(appsJson, null, 2) + '\n');
  console.log('apps.json generated');
}

main();
